other/BookCatalog Razor Pages/BookCatalog/Models/Book.cs
namespace BookCatalog.Models;

public class Book
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Author { get; set; }
    public int PublicationYear { get; set; } 
    public string Genre { get; set; }
    public decimal Price { get; set; }
}

other/BookCatalog Razor Pages/BookCatalog/Controllers/BookCatalogController.cs
using BookCatalog.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookCatalog.Controllers;
public class BookCatalogController : Controller
{
    private readonly ILogger<BookCatalogController> _logger;
    private readonly static List<Book> books = new List<Book>()
    {
        new Book()
        {
            Id = 1,
            Title = "To Kill a Mockingbird",
            Author = "Harper Lee",
            PublicationYear = 1960,
            Genre = "Fiction",
            Price = 7.99m,
            Description = "A novel about the serious issues of race and class in the Deep South, seen through the eyes of a young girl."
        },
        new Book()
        {
            Id = 2,
            Title = "1984",
            Author = "George Orwell",
            PublicationYear = 1949,
            Genre = "Dystopian",
            Price = 8.99m,
            Description = "A chilling tale about totalitarianism and surveillance in a dystopian future."
        },
        new Book()
        {
            Id = 3,
            Title = "The Great Gatsby",
            Author = "F. Scott Fitzgerald",
            PublicationYear = 1925,
            Genre = "Classic",
            Price = 10.50m,
            Description = "A story about the American dream and the excesses of the Jazz Age, narrated by Nick Carraway."
        },
        new Book()
        {
            Id = 4,
            Title = "Pride and Prejudice",
            Author = "Jane Austen",
            PublicationYear = 1813,
            Genre = "Romance",
            Price = 6.99m,
            Description = "A romantic novel that deals with issues of class, marriage, and morality in early 19th-century England."
        },
        new Book()
        {
            Id = 5,
            Title = "The Catcher in the Rye",
            Author = "J.D. Salinger",
            PublicationYear = 1951,
            Genre = "Fiction",
            Price = 9.99m,
            Description = "A coming-of-age story that explores themes of identity, belonging, and alienation."
        }
    };

    public BookCatalogController(ILogger<BookCatalogController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public IActionResult GetAllBooks()
    {
        return View("List", books);
    }

    [HttpGet]
    public IActionResult GetBook(int id)
    {
        var res = books.FirstOrDefault(book => book.Id == id);
        if (res == null)
            return View("Error", $"Cannot find any record with id {id} :c");

        return View("Book", res);
    }

    public IActionResult UpdateBook(int id)
    {
        var res = books.FirstOrDefault(book => book.Id == id);
        if (res == null)
            return View("Error", $"Cannot find any record with id {id} :c");

        return View("Edit", res);
    }

    [HttpPost]
    [HttpPut]
    public IActionResult UpdateBook(Book bookToUpdate)
    {
        var book = books.FirstOrDefault(book => book.Id == bookToUpdate.Id);
        if (book == null)
            return View("Error", $"Cannot find any record with id {bookToUpdate.Id} :c");
        book.Title = bookToUpdate.Title;
        book.Author = bookToUpdate.Author;
        book.Genre = bookToUpdate.Genre;
        if (bookToUpdate.PublicationYear < 0 || bookToUpdate.PublicationYear > DateTime.Today.Year)
            return View("Error", $"Wrong record :c");
        book.PublicationYear = bookToUpdate.PublicationYear;
        if (bookToUpdate.Price < 0)
            return View("Error", $"Wrong record :c");
        book.Price = bookToUpdate.Price;

        return RedirectToAction("GetAllBooks");
    }

    public IActionResult CreateBook()
    {
        return View("Create");
    }

    [HttpPost]
    public IActionResult CreateBook(Book book)
    {
        book.Id = books.Last().Id + 1;
        books.Add(book);

        return RedirectToAction("GetAllBooks");
    }

    public IActionResult DeleteBook(int id)
    {
        var book = books.Find(x => x.Id == id);
        if (book == null)
            return View("Error", $"Cannot find any record with id {id} :c");

        books.Remove(book);
        return RedirectToAction("GetAllBooks");
    }
}

other/BookCatalog Razor Pages/BookCatalog/Views/BookCatalog/Book.cshtml
@model BookCatalog.Models.Book

@{
    ViewData["Title"] = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mb-4 text-center">Book Details</h1>
<hr class="mb-4" />
<div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
        <form asp-action="UpdateBook" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>

            <div class="form-floating mb-3">
                <input disabled asp-for="Title" class="form-control" />
                <label asp-for="Title">Title</label>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <textarea disabled asp-for="Description" class="form-control" style="height: 150px; padding: 7% 2%; resize: none;"></textarea>
                <label asp-for="Description">Description</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input disabled asp-for="Author" class="form-control" />
                <label asp-for="Author">Author</label>
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input disabled asp-for="PublicationYear" class="form-control"/>
                <label asp-for="PublicationYear">Publication Year</label>
                <span asp-validation-for="PublicationYear" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input disabled asp-for="Genre" class="form-control" />
                <label asp-for="Genre">Genre</label>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input disabled asp-for="Price" class="form-control"/>
                <label asp-for="Price">Price</label>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-center">
                <a asp-action="GetAllBooks" class="btn btn-secondary btn-lg">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

other/BookCatalog Razor Pages/BookCatalog/Views/BookCatalog/Create.cshtml
@model BookCatalog.Models.Book

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mb-4 text-center">Edit Book Details</h1>
<hr class="mb-4" />
<div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
        <form asp-action="CreateBook" method="post" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>

            <div class="form-floating mb-3">
                <input asp-for="Title" class="form-control" placeholder="Enter Book Title" />
                <label asp-for="Title">Title</label>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Author" class="form-control" placeholder="Enter Author Name" />
                <label asp-for="Author">Author</label>
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="PublicationYear" class="form-control" placeholder="Enter Publication Year" />
                <label asp-for="PublicationYear">Publication Year</label>
                <span asp-validation-for="PublicationYear" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Genre" class="form-control" placeholder="Enter Genre" />
                <label asp-for="Genre">Genre</label>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Price" class="form-control" placeholder="Enter Price" />
                <label asp-for="Price">Price</label>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <textarea asp-for="Description" class="form-control" placeholder="Enter Book Description" style="height: 150px; resize: none;"></textarea>
                <label asp-for="Description">Description</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-between">
                <input type="submit" value="Save Changes" class="btn btn-success btn-lg" />
                <a asp-action="GetAllBooks" class="btn btn-secondary btn-lg">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

other/BookCatalog Razor Pages/BookCatalog/Views/BookCatalog/Edit.cshtml
@model BookCatalog.Models.Book

@{
    ViewData["Title"] = "Edit Book";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mb-4 text-center">Edit Book Details</h1>
<hr class="mb-4" />
<div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
        <form asp-action="CreateBook" method="post" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>

            <div class="form-floating mb-3">
                <input asp-for="Title" class="form-control" placeholder="Enter Book Title" />
                <label asp-for="Title">Title</label>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Author" class="form-control" placeholder="Enter Author Name" />
                <label asp-for="Author">Author</label>
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="PublicationYear" class="form-control" placeholder="Enter Publication Year" />
                <label asp-for="PublicationYear">Publication Year</label>
                <span asp-validation-for="PublicationYear" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Genre" class="form-control" placeholder="Enter Genre" />
                <label asp-for="Genre">Genre</label>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Price" class="form-control" placeholder="Enter Price" />
                <label asp-for="Price">Price</label>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <textarea asp-for="Description" class="form-control" placeholder="Enter Book Description" style="height: 150px; resize: none;"></textarea>
                <label asp-for="Description">Description</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-between">
                <input type="submit" value="Save Changes" class="btn btn-success btn-lg" />
                <a asp-action="GetAllBooks" class="btn btn-secondary btn-lg">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

other/BookCatalog Razor Pages/BookCatalog/Views/BookCatalog/List.cshtml
@model System.Collections.Generic.List<BookCatalog.Models.Book>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">
    <h1 class="mb-4 text-center">Book Catalog</h1>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Year</th>
                    <th>Genre</th>
                    <th>Price</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-action="GetBook" asp-controller="BookCatalog" asp-route-id="@item.Id" role="button" class="btn btn-outline-primary btn-sm me-2">
                                @item.Id
                            </a>
                        </td>
                        <td>@item.Title</td>
                        <td>@item.Author</td>
                        <td>@item.PublicationYear</td>
                        <td>@item.Genre</td>
                        <td>@item.Price.ToString("C")</td>
                        <td>
                            <div class="d-flex justify-content-md-between">
                                <a asp-action="UpdateBook" asp-controller="BookCatalog" asp-route-id="@item.Id" role="button" class="btn btn-outline-primary btn-sm me-2">
                                    Edit
                                </a>
                                <form asp-action="DeleteBook" asp-controller="BookCatalog" asp-route-id="@item.Id" method="post" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="text-center mb-4">
            <a asp-action="CreateBook" asp-controller="BookCatalog" class="btn btn-success btn-lg">
                Create
            </a>
        </div>
    </div>
</div>

other/BookCatalog Razor Pages/BookCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookCatalog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookCatalog.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="BookCatalog" asp-action="Index">BookCatalog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookCatalog" asp-action="Index">BookCatalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookCatalog" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="max-width: 80%">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookCatalog - <a asp-area="" asp-controller="BookCatalog" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>